### PR TITLE
Testing results by taking screenshot

### PR DESCRIPTION
**Pull request by unlight**
Hi.
This add additional testing by compare expected picture and actual screenshot (by phantomjs).
To run test, do:
`npm run verify`
I have added such test only for `example2.html`, if you like it, I will add others.

### CODE REVIEW

**Comment by FremyCompany** [comment]
Awesome! I should have been doing something like this from day one, instead of manually checking the files (and therefore ending up being too lazy to execute all the tests, of course). 

Thanks a lot for caring to contribute back your work! I made a pull request on your pull request with various minor change proposals. Feel free to have a look.

Would you mind adding a command line I could use to take a screenshot of a page given as argument and save it as {html_filename}.png? Then, I'll write a test runner which will execute your test on all pages which have a companion png by generating the . This would be a great way to find out about regressions.

One more suggestion, I would rather see the /tmp folder deleted and added in the base ".gitignore", it will look cleaner at first glance ;-)

**Comment by unlight** [comment]
Added more tests, test `example13.html` do not passes.
I think it should be splitted to several: width < 400, 400 < w < 590, and width > 590. I added viewportWidth/viewportHeight options.

**Comment by FremyCompany** [comment]
It seems the 'example13' issue is related to Media Queries, because the test passes in IE for which I don't need to compute the cascaded style on my own. I"ll investigate this.

**Comment by FremyCompany** [comment]
Example 13 is now working in FF/Chrome as well, I fixed the issue.

**Comment by FremyCompany** [comment]
Someone implemented a javascript-based solution that's a bit more lightweight than picture-comparison. I just merged that PR so there shouldn't be a need for this PR anymore.

**Pull request closed without merging**
